{
 "title": "DevOps Observability Lab",
 "tags": [
  "devops",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_requests_total)", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_errors_total)", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Errors In Last Minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_errors_total[1m]))",
     "legendFormat": "errors/min"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_request_duration_seconds_sum[1m])) / sum(rate(app_request_duration_seconds_count[1m]))",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "Request Rate By Path And Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path, status) (rate(app_requests_total[1m]))",
     "legendFormat": "{{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Application Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(app_errors_total[1m]))",
     "legendFormat": "errors/min"
    }
   ]
  },
  {
   "title": "Filtered JSON Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{service=\"observability-app\"} | json | level=\"error\""
    }
   ]
  }
 ]
}